apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-class
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.31.40.90
    path: /var/nfsshare/
