apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc

